[package]
name = "testci"
version = "0.3.0"
edition = "2024"
repository = "https://github.com/elfedy/testrelease"

[dependencies]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
